name: TunaLands
main: com.salkcoding.tunalandsBC.TunaLands
version: 1.1.5-SNAPSHOT
description: Protect lands with some money
api-version: 1.18
author: Salk_Coding
depend:
  - Metamorphosis
  - BukkitLinked
commands:
  tunaland:
    description: Base command
    usage: /tunaland help, /tl help
    aliases: [ tl ]