name: TunaLands
main: com.salkcoding.tunalandsbc.TunaLands
version: 1.0.0-SNAPSHOT
description: Protect lands with some money
api-version: 1.16
author: Salk_Coding
depend: [KotlinBukkitAPI]
commands:
  land:
    description: Base command
    usage: /land help, /ld help
    aliases: [ld]